# Generated by Django 4.1.5 on 2023-01-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('storage', '0002_remove_storage_name_storage_branch_storage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_storage', to='products.product', unique=True, verbose_name='Наименование товара'),
        ),
    ]
