# Generated by Django 4.1.5 on 2023-01-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('storage', '0003_alter_storage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_storage', to='products.product', verbose_name='Наименование товара'),
        ),
    ]
